### ISSUE TITLE
INSUFFICIENT_OUTPUT_AMOUNT Error

### ISSUE THREAD

**Issue by ifunanya55** [vincor1986/merlin#2]
Anytime i try to do a swap, i always get the Insufficient Output Amount error. I believe it is an issue regarding slippage and in the script, i don't see anywhere i can input my slippage and am running out of gas now xD. I haven't made any successful trade yet because of the slippage error

**Comment by vincor1986** [comment]
Thanks for getting in touch, I'm sorry to hear merlin hasn't been performing great.

I chose not to build in a slippage setting because I thought it better to calculate whether there would be a profit on the trade, and just reject the trade if there was no profit. The "minOutput" variable within the config.js file controls this. The calculation for "minOutput" is <total trade amount (inputAmount)> + <anticipated trade cost (tradeCost)>. So if the exchange router contract determines you will receive less back than this "minOutput" amount it will revert the tx. I thought this a more effective means of dealing with slippage because it maximises opportunity for profit. It should be noted that the "tradeCost" variable in config.js should be recalculated and adjusted accordingly if you change any of the gasPrice variables.

However, in my experience and it seems in the experience of others, slippage has been too excessive for merlin to work well on these sorts of exchanges over recent months. I can say that it was working really well in May and June of this year, but since then it seems to be just returning insufficient output amount errors (i.e. - you would lose more if those trades went through successfully).

I can only attritbute this decline in performance to a reduction in volume on PancakeSwap since June, although in all honesty I am not 100% sure about this. Because of the way that prices are calculated on exchanges such as PancakeSwap, every transaction affects the next transaction's prices, so the more people that use Merlin or similiar types of bots, the lower likelihood that a trade will be successful as more people are trying to get that profitable trade before it disappears. 

I mention in the readme that I would advise only using the bot at peak volume, by that I mean when asset prices are soaring / plummetting across the board. This is because there will be more transactions going through the most popular assets's liquidity pools (the pools looked at by Merlin) and there is an increased chance that short periods (10 - 20 second periods) will come where there is an influx of orders that push the price to an advantageous level, whereby unavoidable slippage may not exceed profit. 

I hope this makes sense, and is in some way helpful. Thanks again for getting in touch and if you need anything else please let me know.

**Comment by ifunanya55** [comment]
What about adding a slippage feature in though

**Comment by vincor1986** [comment]
The only way it could escape the error is by enabling the transactions to make a loss. As it stands at this point, if a tx is reverted with an insufficient output amount error, it is because you would have made a loss on the trade. Adding a slippage rate would also potentially cut out successful trades where slippage exceeds the user-defined slippage threshold but are still profitable trades.

I appreciate that it's annoying that these insufficient ouput amount errors are so common and consistent at the present time, but I wouldn't attribute this to the lack of a slippage rate, as it's not as if there is no slippage mechanism to handle slippage. It's more that prices are just returning to an unprofitable level too quickly. The current mechanism is in place to reduce losses, and will only return an insufficient output amount error if you were going to make a loss on the trade - so in one sense, every IOA error is a favourable result compared to that trade going through as if it were successful, you would pay for the full transaction in gas (which is higher than a revert) and you would receive less base currency back than you sent in.

**Comment by vincor1986** [comment]
Please note that I have updated the "important" notice of the readme to include some details and supporting evidence about my theory on how volume on the exchange affects merlin's performance. I hope that helps.
